config/routes.rb
Rails.application.routes.draw do
  resources :qr_code_readers
  resources :efemerides
  resources :events
  resources :eventos
  resources :paquetes
  resources :precios
  resources :horarios
  resources :pets
  resources :respuesta
  devise_for :users
  resources :comentarios
  resources :qr_codes, only: [:new, :create]
  get 'index/principal'

  root "pets#index"
  
  get 'ras' => 'principal#ras'
  get 'ras2' => 'principal#ras2'
  get 'casahidalgo' => 'pets#casahidalgo'
  get 'casadecendienteshidalgo' => 'pets#casadecendienteshidalgo'
  get 'show' => 'pets#show'
  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'principal/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  has_many :respuestum, dependent: :destroy
end

app/models/efemeride.rb
class Efemeride < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :pet
end

app/models/paquete.rb
class Paquete < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :horarios, dependent: :destroy
  has_many :paquetes, dependent: :destroy
  has_many :precios, dependent: :destroy
end

app/models/precio.rb
class Precio < ApplicationRecord
  belongs_to :pet
end

app/models/qr_code_reader.rb
class QrCodeReader < ApplicationRecord
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :comentario
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[ :index, :show, :casahidalgo, :casadecendienteshidalgo ]
  
  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

   def casahidalgo
  end

  def casadecendienteshidalgo
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Museos ha sido creado.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Museo ha sido modificado.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Museo ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :description, :image)
    end
end

app/helpers/efemerides_helper.rb
module EfemeridesHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/paquetes_helper.rb
module PaquetesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, id: :pet_name, :class => 'form-control', :placeholder => "Nombre del Museo" %>
  </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= form.label :description, "Descripción" %>
    <%= form.text_area :description, id: :pet_description, :class => 'form-control', :rows => "10", :cols => "30" %>
  </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= form.label :image, "Foto" %>
    <%= form.file_field :image, id: :pet_image, :class => 'form-control' %>
  </div>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", :class => "btn btn-primary"  %>
  </div>
<% end %>

app/views/pets/casahidalgo.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="titulos">Museo Casa de Hidalgo</h1>
    <img src="http://www.mexicoescultura.com/galerias/espacios/principal/casa_de_hidalgo.jpg" class="img-responsive" style=" width: 25%">
    <br>
  </div>
</div>

<div class="container">
  

    <div class="col-md-8">
      <div class="page-header">
        <h2 style="display:inline"> Descripción </h2>
        <span class="label label-default">New</span>
      </div>

      <p class="titulos">Antigua y bella casona de finales del siglo XVIII, con un encantador patio en cuyo alrededor se disponen las habitaciones de la que fuera la morada de Miguel Hidalgo durante su estancia en esta población. El cura Hidalgo habitó en esta casa hasta el año de 1810 y en ese entonces se le conocía como Casa del Diezmo.</p>
      <p class="titulos">Durante la Guerra de Independencia la casa fue ocupada por diversos bandos y se dice, saqueada en varias ocasiones.
        Fue declarada Monumento Nacional en el año de 1863 por Benito Juárez.</p>
      <p class="titulos">Se conviritó en museo en 1946: En los aposentos se recreó el ambiente y el mobiliario de la época como escenario para exhibir algunos de los objetos personales del prócer y documentos de la guerra de Independencia. En el museo se resguardan vestimentas sacerdotales un estandarte de la Virgen de Guadalupe, el primer bando de abolición de la esclavitud y una urna funeraria con los restos de Miguel Hidalgo y Costilla.</p>
      <br>
      <hr>
      <br>

      <h2>Precios </h2>
      <p align="justify">$15 Estudiantes</p>
      <p align="justify">$35 Visitantes</p>

      <br>
      <hr>
      <br>

      <h2>Paquetes</h2>
      <p align="justify">Aplica restricciones.</p>

      <br>
      <hr>
      <br>

      <h2>Realidad Aumentada</h2>
      <p>Da clic al botón para acceder al apartado.</p>

      <a class="btn btn-default" href="<%= ras_path %>">Ir</a>
      <br>
      <hr>
      <br>

      <div class="row">

    <div align="center">
        <h2 style="display:inline">
          Ubicación
        </h2>
        <br>
        <br>
            <style type="text/css">
      /* Set a size for our map container, the Google Map will take up 100% of this container */
      #map {
        width: 520px;
        height: 320px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
      }
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnC-d0W6Z0oVxxvgxYgEW86bXVhWuwnZU"></script>

      <script type="text/javascript">
          // When the window has finished loading create our google map below
          google.maps.event.addDomListener(window, 'load', init);

          function init() {
              // Basic options for a simple Google Map
              // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
              var mapOptions = {
                  // How zoomed in you want the map to start at (always required)
                  zoom: 16,

                  // The latitude and longitude to center the map (always required)
                  center: new google.maps.LatLng(21.15638999999999,-100.93589159999999), // Museo Casa Hidalgo

                  // How you would like to style the map.
                  // This is where you would paste any style found on Snazzy Maps.
                  styles: [ {   "featureType":"landscape",    "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":50.2     },      {       "lightness":-34.8     },      {       "gamma":1     }   ] },  {   "featureType":"road.highway",   "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":-19.8      },      {       "lightness":-1.8      },      {       "gamma":1     }   ] },  {   "featureType":"road.arterial",    "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":72.4     },      {       "lightness":-32.6     },      {       "gamma":1     }   ] },  {   "featureType":"road.local",   "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":74.4     },      {       "lightness":-18     },      {       "gamma":1     }   ] },  {   "featureType":"water",    "stylers":[     {       "hue":"#00FFA6"     },      {       "saturation":-63.2      },      {       "lightness":38      },      {       "gamma":1     }   ] },  {   "featureType":"poi",    "stylers":[     {       "hue":"#FFC300"     },      {       "saturation":54.2     },      {       "lightness":-14.4     },      {       "gamma":1     }   ] }]
              };


              // Get the HTML DOM element that will contain your map
              // We are using a div with id="map" seen below in the <body>
              var mapElement = document.getElementById('map');

              // Create the Google Map using our element and options defined above
              var map = new google.maps.Map(mapElement, mapOptions);

              // Let's also add a marker while we're at it
              var image = 'https://cdn2.iconfinder.com/data/icons/location-map-simplicity/512/museum-128.png'
              var marker = new google.maps.Marker({
                  position: new google.maps.LatLng(21.15638999999999,-100.93589159999999),
                  map: map,
                  title: 'Casa Hidalgo',
                  icon: image
              });
          }
      </script>
      <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnC-d0W6Z0oVxxvgxYgEW86bXVhWuwnZU&callback=initMap">
    </script>

      <div id="map", style="width: 95%", style="height: height: 50%" ></div>
      </div>
    </div>

      <br>
      <hr>
      <br>

    </div>

    <div class="col-md-4">
      <div class="page-header">
        <div id="noty_layout__topRight" class="noty_layout">
            <script>
              new Noty({
                text: 'Efemérdes 21 de Agosto',
                animation: {
                  open: 'animated bounceInRight', // Animate.css class names
                  close: 'animated bounceOutRight' // Animate.css class names
                }
              }).show();

              new Noty({
                text: '1842.—Muere Leona Vicario, insurgente mexicana durante la guerra de independencia de México.',
                animation: {
                  open: 'animated bounceInRight', // Animate.css class names
                  close: 'animated bounceOutRight' // Animate.css class names
                }
              }).show();
            </script>
          </div>
      </div>
      <h2>Horairos </h2>
      <ul>
        <li>
          Martes    9:00–17:45
        </li>
        <li>
          Miércoles 9:00–17:45
        </li>
        <li>
          Jueves    9:00–17:45
        </li>
        <li>
          Viernes   9:00–17:45
        </li>
        <li>
          Sábado    9:00–17:45
        </li>
        <li>
          Domingo   9:00–16:45
        </li>
        <li>
          Lunes Cerrado
        </li>
      </ul>
    </div>

    <div class="col-md-4">
      <div class="page-header">
        <div style="text-align:center;width:400px;padding:1em 0;"> <h2><a style="text-decoration:none;" href="http://www.zeitverschiebung.net/es/city/4023117"><span style="color:gray;">Hora actual en</span><br />Dolores Hidalgo Cuna de la Independencia Nacional, México</a></h2> <iframe src="https://www.zeitverschiebung.net/clock-widget-iframe-v2?language=es&timezone=America%2FMexico_City" width="100%" height="150" frameborder="0" seamless></iframe> <small style="color:gray;">&copy; <a href="http://www.zeitverschiebung.net/es/" style="color: gray;">Diferencia horaria</a></small> </div>

      </div>

    </div>



  </div>

</div>

</div>

app/views/pets/edit.html.erb
<div class="container">
    <h1>Editar  Museo</h1>
  <div class="row">
    <div class="col-md-6">
    <%= render 'form', pet: @pet %>
    </div>
  </div>
   <%= link_to 'Mostrar', @pet, :class => "btn btn-primary" %> |
   <%= link_to 'Regresar', pets_path, :class => "btn btn-primary", :style => "color: white" %>
</div>

app/views/pets/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- elementos del slider-->
    <link type="text/css" href="dist/skitter.css" media="all" rel="stylesheet" />
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <scrpt type="text/javascript" src="dist/jquery.skitter.min.js"></script>
    <!-- Init Skitter -->
    <script type="text/javascript" language="javascript">
      $(document).ready(function() {
        $('.skitter-large').skitter({
          
        });
      });
    </script>
    <!--termina elementos del slider-->


    <title></title>
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/small-business.css" rel="stylesheet">
</head>
<body>
    <!-- Page Content -->
    <br>
    <div class="container">
        <!-- Heading Row -->
        <div class="row">
            <div class="col-md-8">

              <!-- start slider -->
      <div id="page">

        <div id="content" class="responsive">
          <div class="skitter skitter-large with-dots">
            <ul>
              <li><a href="/show?id=8"><img src="http://i.imgur.com/iAHAH9Z.jpg" class="circles" ></a><div class="label_text"><p>El Museo de la Independencia se localiza dentro de un inmueble construido a finales del siglo XVIII por el filántropo don Francisco Miguel González... <a href="/show?id=8" class="btn btn-small btn-yellow">Más información</a></p></div></li>
              <li><a href="/show?id=10"><img src="http://i.imgur.com/KSzoDoM.jpg" class="circlesInside" ></a><div class="label_text"><p>El Museo Bicentenario cuenta con un total de 827 piezas de la celebración del primer centenario de la Independencia, entre las que destacan joyas, armas, música... <a href="/show?id=10" class="btn btn-small btn-yellow">Más información</a></p></div></li>
              <li><a href="/show?id=10"><img src="http://i.imgur.com/Dq3Njbt.jpg" class="circlesRotate" ></a><div class="label_text"><p>Durante la Guerra de Independencia la casa fue ocupada por diversos bandos y se dice, saqueada en varias ocasiones... <a href="/show?id=10" class="btn btn-small btn-yellow">Más información</a></p></div></li>
            </ul>
          </div>
        </div>

      </div>
                  <!-- end slider -->
                <!--<img class="img-responsive img-rounded" src="http://placehold.it/900x350" alt=""> -->
  </div>
  <!-- /.col-md-8 -->
  <div class="col-md-4">
      <h1>Museos en la ciudad de Dolores Hidalgo</h1>
      <p style="text-align: justify;">Esta aplicación te permitira echar un vistazo a los museos que existen en Dolores Hidalgo C.I.N. De una forma diferente nunca antes vista en este tipo de atracciónes!!</p>
      <!--<a class="btn btn-primary btn-lg" href="#">Realidad aumentada</a> -->
  </div>
  <!-- /.col-md-4 -->
</div>
<!-- /.row -->
<hr>
<!-- Call to Action Well -->
<div class="row">
  <div class="col-lg-12">
      <div class="well text-center" style="background-color: #e95420; color: white">
          Dolores Hidalgo Cuna de la Independencia Nacional es un lugar lleno de riquezas culturales que tu puedes apreciar en sus museos!
      </div>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
  <p id="notice"><%= notice %></p>

  <div id="container" align="center">

    <% @pets.each do |pet| %>
    <div class="item" style="width: 100%; ">
      <div class="thumbnail">
        <%= pet.name %><br>
        <a href="<%= show_path(:id => pet.id) %>"> <%= image_tag(pet.image, :class => 'img-responsive') %></a>
        <br>
        <%= pet.description %><br>
        <% if user_signed_in? %>
        <div class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Mostrar', pet, :class => 'btn' %>
          <%= link_to 'Editar', edit_pet_path(pet), :class => 'btn' %>
          <%= link_to 'Eliminar', pet, method: :delete, data: { confirm: 'Esta seguro?' }, :class => 'btn' %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>

    <br>

</div>

<script type="text/javascript">
    var $container = $('#container')
        // options
        $container.masonry({
        columnWidth: 200,
        itemSelector: '.item'
    });

  $(window).load(function(){
    var $container = $('#container');
        // options
      $container.masonry({
          columnWidth: 200,
          itemSelector: '.item'
    });
  })
</script>

  </body>

  
</html>

app/views/pets/new.html.erb
<div class="container">
    <h1>Crea un nuevo Museo</h1>
  <div class="row">
    <div class="col-md-6">
    <%= render 'form', pet: @pet %>
    </div>
  </div>
   <p> <%= link_to 'Regresar', pets_path, :class => "btn btn-primary", :style => "color: white" %></p>
</div>

app/views/pets/show.html.erb
<div class="container">


</div>
<div class="jumbotron">
  <div class="container" align="center" >
    <div class="outer">
      <%= image_tag(@pet.image, :style => 'box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19); width:100%; height: 100%; ') %>
        <div class="overlay">
          <h1 class="titulos"><%= @pet.name %></h1>
        </div>
    </div>
  </div>
</div>

<div class="container" align="center">

    <div class="col-md-8">
      <div class="page-header">
        <h2 style="display:inline"> Descripción </h2>
      </div>
      
      <p><%= @pet.description %></p>
      <br>
      <hr>
      <br>

      <h2>Precios </h2>

      <% @pet.precios.each do |precio| %>
        <tr>
          $<%= precio.precio %> ->
          <%= precio.tipo %>
          <% if user_signed_in? %>
          <br><br>
          <%= link_to 'Editar', edit_precio_path(precio), :class => "btn btn-primary" %><br><br>
          <%= link_to 'Eliminar', precio, method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-primary" %><br>
        </tr>
        <% end %>
      <% end %>

    <br>
    <% if user_signed_in? %>
    <%= link_to 'Nuevo Precio', new_precio_path(:id => @pet.id), :class => "btn btn-primary" %>
    <% end %>
      <br>
      <hr>
      <br>

      <h2>Paquetes</h2>
        <br>
      <% @pet.paquetes.each do |paquete| %>
        <tr>
          <h4><%= paquete.nombre %></h4>
          <%= paquete.tipo %><br>
          <%= paquete.descripcion %><br>
          <% if user_signed_in? %>
          <br>
          <%= link_to 'Editar', edit_paquete_path(paquete), :class => "btn btn-primary" %><br><br>
          <%= link_to 'Eliminar', paquete, method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-primary" %><br>
            <% end %>
        </tr>
      <% end %>
  <br>
  <% if user_signed_in? %>
  <%= link_to 'Nuevo Paquete', new_paquete_path(:id => @pet.id), :class => "btn btn-primary" %>
  <% end %>

      <br>
      <hr>
      <br>

  <div class="row">

    <div align="center">
        <h2 style="display:inline">
          Ubicación
        </h2>
        <br>
        <br>
      <style type="text/css">
      /* Set a size for our map container, the Google Map will take up 100% of this container */
        #map {
          width: 520px;
          height: 320px;
          box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
        }
      </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnC-d0W6Z0oVxxvgxYgEW86bXVhWuwnZU"></script>

      <script type="text/javascript">
          // When the window has finished loading create our google map below
          google.maps.event.addDomListener(window, 'load', init);

          function init() {
              // Basic options for a simple Google Map
              // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
              var mapOptions = {
                  // How zoomed in you want the map to start at (always required)
                  zoom: 17,

                  // The latitude and longitude to center the map (always required)
                  center: new google.maps.LatLng(21.1574278,-100.9345075), // Museo Casa Hidalgo

                  // How you would like to style the map.
                  // This is where you would paste any style found on Snazzy Maps.
                  styles: [ {   "featureType":"landscape",    "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":50.2     },      {       "lightness":-34.8     },      {       "gamma":1     }   ] },  {   "featureType":"road.highway",   "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":-19.8      },      {       "lightness":-1.8      },      {       "gamma":1     }   ] },  {   "featureType":"road.arterial",    "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":72.4     },      {       "lightness":-32.6     },      {       "gamma":1     }   ] },  {   "featureType":"road.local",   "stylers":[     {       "hue":"#FFAD00"     },      {       "saturation":74.4     },      {       "lightness":-18     },      {       "gamma":1     }   ] },  {   "featureType":"water",    "stylers":[     {       "hue":"#00FFA6"     },      {       "saturation":-63.2      },      {       "lightness":38      },      {       "gamma":1     }   ] },  {   "featureType":"poi",    "stylers":[     {       "hue":"#FFC300"     },      {       "saturation":54.2     },      {       "lightness":-14.4     },      {       "gamma":1     }   ] }]
              };


              // Get the HTML DOM element that will contain your map
              // We are using a div with id="map" seen below in the <body>
              var mapElement = document.getElementById('map');

              // Create the Google Map using our element and options defined above
              var map = new google.maps.Map(mapElement, mapOptions);

              // Let's also add a marker while we're at it
              var image = 'https://cdn2.iconfinder.com/data/icons/location-map-simplicity/512/museum-128.png'
              var marker = new google.maps.Marker({
                  position: new google.maps.LatLng(21.15638999999999,-100.93589159999999),
                  map: map,
                  title: 'Casa Hidalgo',
                  icon: image
              })
              var marker2 = new google.maps.Marker({
                  position: new google.maps.LatLng(21.1584295,-100.9353101),
                  map: map,
                  title: 'Museo Independencia',
                  icon: image
              })
              var marker3 = new google.maps.Marker({
                  position: new google.maps.LatLng(21.1574353,-100.9327533),
                  map: map,
                  title: 'Casa Museo José Alfredo Jiménez',
                  icon: image
              })
              var marker4 = new google.maps.Marker({
                  position: new google.maps.LatLng(21.1571429,-100.9353776),
                  map: map,
                  title: 'Casa de los Descendientes',
                  icon: image
              })
              var marker5 = new google.maps.Marker({
                position: new google.maps.LatLng(21.1581235,-100.9346408),
                map: map,
                title: 'Museo Bicentenario',
                icon: image
              });
          }
      </script>
      <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnC-d0W6Z0oVxxvgxYgEW86bXVhWuwnZU&callback=initMap">
      </script>

      <div id="map" style="width: 100%"></div>
      <br>
      </div>
  </div>
    </div>
            
      <br>
      <hr>
      <br>

    <div class="col-md-4">
      <h2>Horarios </h2>
          <br>
          <% @pet.horarios.each do |horario| %>

          <%= horario.dia %> ->
          <%= horario.horai %> -
          <%= horario.horaf %>
          <% if user_signed_in? %>
          <br>
          <%= link_to 'Editar', edit_horario_path(horario) , :class => "btn btn-primary" %><br><br>
          <%= link_to 'Eliminar', horario, method: :delete, data: { confirm: 'Estas seguro?' }, :class => "btn btn-primary" %><br>
          <% end %>
       <% end %>
     <br>
      <% if user_signed_in? %>
      <%= link_to 'Nuevo Horario', new_horario_path(:id => @pet.id), :class => "btn btn-primary", :style => "color: white;" %>
      <% end %>
    </div>

    <div class="col-md-4" align="center">
      <div class="page-header" style="width: 100%" >
        <div style="text-align:center;width:400px;padding:1em 0; width: 100%" > <h2><a style="text-decoration:none;" href="http://www.zeitverschiebung.net/es/city/4023117"><span >Hora actual en</span><br />Dolores Hidalgo Cuna de la Independencia Nacional, México</a></h2> <iframe src="https://www.zeitverschiebung.net/clock-widget-iframe-v2?language=es&timezone=America%2FMexico_City" width="100%" height="150" frameborder="0" seamless></iframe> <small>&copy; <a href="http://www.zeitverschiebung.net/es/">Diferencia horaria</a></small> </div>

      </div>

    </div>

    <%- if user_signed_in? %>
      <h3>Editar éste museo o volver a museos</h3>
      <%= link_to 'Editar', edit_pet_path(@pet), :class => "btn btn-primary", :style => "color: white" %> |
      <%= link_to 'Regresar', pets_path, :class => "btn btn-primary", :style => "color: white" %>
      <hr>
    <% end -%>
  </div>

</div>

</div>