config/routes.rb
Rails.application.routes.draw do
  resources :qr_code_readers
  resources :efemerides
  resources :events
  resources :eventos
  resources :paquetes
  resources :precios
  resources :horarios
  resources :pets
  resources :respuesta
  devise_for :users
  resources :comentarios
  resources :qr_codes, only: [:new, :create]
  get 'index/principal'

  root "pets#index"
  
  get 'ras' => 'principal#ras'
  get 'ras2' => 'principal#ras2'
  get 'casahidalgo' => 'pets#casahidalgo'
  get 'casadecendienteshidalgo' => 'pets#casadecendienteshidalgo'
  get 'show' => 'pets#show'
  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'principal/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  has_many :respuestum, dependent: :destroy
end

app/models/efemeride.rb
class Efemeride < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :pet
end

app/models/paquete.rb
class Paquete < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :horarios, dependent: :destroy
  has_many :paquetes, dependent: :destroy
  has_many :precios, dependent: :destroy
end

app/models/precio.rb
class Precio < ApplicationRecord
  belongs_to :pet
end

app/models/qr_code_reader.rb
class QrCodeReader < ApplicationRecord
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :comentario
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/efemerides_controller.rb
class EfemeridesController < ApplicationController
  before_action :set_efemeride, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[ :index ]
  # GET /efemerides
  # GET /efemerides.json
  def index
    @efemerides = Efemeride.all
  end

  # GET /efemerides/1
  # GET /efemerides/1.json
  def show
  end

  # GET /efemerides/new
  def new
    @efemeride = Efemeride.new
  end

  # GET /efemerides/1/edit
  def edit
  end

  # POST /efemerides
  # POST /efemerides.json
  def create
    @efemeride = Efemeride.new(efemeride_params)

    respond_to do |format|
      if @efemeride.save
        format.html { redirect_to @efemeride, notice: 'Efemeride ha sido creada.' }
        format.json { render :show, status: :created, location: @efemeride }
      else
        format.html { render :new }
        format.json { render json: @efemeride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /efemerides/1
  # PATCH/PUT /efemerides/1.json
  def update
    respond_to do |format|
      if @efemeride.update(efemeride_params)
        format.html { redirect_to @efemeride, notice: 'Efemeride ha sido actualizada.' }
        format.json { render :show, status: :ok, location: @efemeride }
      else
        format.html { render :edit }
        format.json { render json: @efemeride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /efemerides/1
  # DELETE /efemerides/1.json
  def destroy
    @efemeride.destroy
    respond_to do |format|
      format.html { redirect_to efemerides_url, notice: 'Efemeride ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_efemeride
      @efemeride = Efemeride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def efemeride_params
      params.require(:efemeride).permit(:numero, :descripcion)
    end
end

app/helpers/efemerides_helper.rb
module EfemeridesHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/paquetes_helper.rb
module PaquetesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/views/efemerides/_form.html.erb
<%= form_with(model: efemeride, local: true) do |form| %>
  <% if efemeride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(efemeride.errors.count, "error") %> prohibited this efemeride from being saved:</h2>

      <ul>
      <% efemeride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero, id: :efemeride_numero, :class => "form-control" %>
  </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :efemeride_descripcion,  :class => 'form-control', :rows => "10", :cols => "30"  %>
  </div>
  </div>

  <div class="actions">
    <%= form.submit  "Guardar", :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/efemerides/edit.html.erb
<div class="container">
    <h1>Editar</h1>
  <div class="row">
    <div class="col-md-6">
    <%= render 'form', efemeride: @efemeride %>
    </div>
  </div>
   <p> <%= link_to 'Ver', @efemeride %> |
   <%= link_to 'Salir', efemerides_path %> </p>
</div>

app/views/efemerides/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Efemerides del mes</h1>

<table class="table table-striped">

  <tbody>
    <% @efemerides.each do |efemeride| %>
      <tr>
        <h1><%= efemeride.numero %></h1>
        <br>
        <%= efemeride.descripcion %><br>
        <% if user_signed_in? %>
        <%= link_to 'Mostrar', efemeride %>
        <%= link_to 'Edit', edit_efemeride_path(efemeride) %>
        <%= link_to 'Eliminar', efemeride, method: :delete, data: { confirm: '¿Esta seguro?' } %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'Nueva Efemeride', new_efemeride_path, :class => "btn btn-primary", :style => "color: white;" %>
<% end %>
<br>
<hr>
<br>
</div>

app/views/efemerides/new.html.erb
<div class="container">
    <h1>Nueva Efemeride</h1>
  <div class="row">
    <div class="col-md-6">
  		<%= render 'form', efemeride: @efemeride %>
  		<%= link_to 'Salir', efemerides_path, :class => "btn btn-primary", :style => "color: white" %>
    </div>
    <br>
    <hr>
    <br>    
  </div>

</div>

app/views/efemerides/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @efemeride.numero %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @efemeride.descripcion %>
</p>

<%= link_to 'Editar', edit_efemeride_path(@efemeride) %> |
<%= link_to 'Salir', efemerides_path %>

</div>