config/routes.rb
Rails.application.routes.draw do
  resources :qr_code_readers
  resources :efemerides
  resources :events
  resources :eventos
  resources :paquetes
  resources :precios
  resources :horarios
  resources :pets
  resources :respuesta
  devise_for :users
  resources :comentarios
  resources :qr_codes, only: [:new, :create]
  get 'index/principal'

  root "pets#index"
  
  get 'ras' => 'principal#ras'
  get 'ras2' => 'principal#ras2'
  get 'casahidalgo' => 'pets#casahidalgo'
  get 'casadecendienteshidalgo' => 'pets#casadecendienteshidalgo'
  get 'show' => 'pets#show'
  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'principal/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  has_many :respuestum, dependent: :destroy
end

app/models/efemeride.rb
class Efemeride < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :pet
end

app/models/paquete.rb
class Paquete < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :horarios, dependent: :destroy
  has_many :paquetes, dependent: :destroy
  has_many :precios, dependent: :destroy
end

app/models/precio.rb
class Precio < ApplicationRecord
  belongs_to :pet
end

app/models/qr_code_reader.rb
class QrCodeReader < ApplicationRecord
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :comentario
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/paquetes_helper.rb
module PaquetesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/views/shared/_footer.html.erb
<div class="container well">
  <h2><center>Museos Dolores Hidalgo</center></h2>
</div>

<div id="footer">
    <div class="container">
        <div class="row">
            <center><h3 class="footertext">Copyright 2017</h3> </center>

    	</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag "http://svgshare.com/i/2is.svg", :class => "nav-logo" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= ras_path %>">Realidad Aumentada</a></li>
        <li ><a href="<%= comentarios_path %>">Comentarios</a></li>
        <li><a href="<%= events_path %>">Eventos</a></li>
        <li><a href="<%= efemerides_path %>">Efemérides</a></li>
        <%- if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true" >Descuentos <span class="caret"></span> </a>
            <ul class="dropdown-menu" role="menu" >
              <li><a href="<%= new_qr_code_path %>">Dar Descuento</a></li>
              <li class="divider"></li>
              <li><a href="<%= qr_code_readers_path %>">Registrar Descuento</a></li>
            </ul>
          </li>
        <% end -%>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a href="<%= new_pet_path %>"> Crear Museo </a></li>
            <li><a href="<%= destroy_user_session_path%>" data-method="delete"> Salir </a></li>
        <% end %>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
