config/routes.rb
Rails.application.routes.draw do
  resources :qr_code_readers
  resources :efemerides
  resources :events
  resources :eventos
  resources :paquetes
  resources :precios
  resources :horarios
  resources :pets
  resources :respuesta
  devise_for :users
  resources :comentarios
  resources :qr_codes, only: [:new, :create]
  get 'index/principal'

  root "pets#index"
  
  get 'ras' => 'principal#ras'
  get 'ras2' => 'principal#ras2'
  get 'casahidalgo' => 'pets#casahidalgo'
  get 'casadecendienteshidalgo' => 'pets#casadecendienteshidalgo'
  get 'show' => 'pets#show'
  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'principal/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  has_many :respuestum, dependent: :destroy
end

app/models/efemeride.rb
class Efemeride < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :pet
end

app/models/paquete.rb
class Paquete < ApplicationRecord
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :horarios, dependent: :destroy
  has_many :paquetes, dependent: :destroy
  has_many :precios, dependent: :destroy
end

app/models/precio.rb
class Precio < ApplicationRecord
  belongs_to :pet
end

app/models/qr_code_reader.rb
class QrCodeReader < ApplicationRecord
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :comentario
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/precios_controller.rb
class PreciosController < ApplicationController
  before_action :set_precio, only: [:show, :edit, :update, :destroy]

  # GET /precios
  # GET /precios.json
  def index
    @precios = Precio.all
  end

  # GET /precios/1
  # GET /precios/1.json
  def show
  end

  # GET /precios/new
  def new
    @precio = Precio.new
    @pet = Pet.find(params[:id])
  end

  # GET /precios/1/edit
  def edit
  end

  # POST /precios
  # POST /precios.json
  def create
    @precio = Precio.new(precio_params)

    respond_to do |format|
      if @precio.save
        format.html { redirect_to pets_url }
        format.json { render :show, status: :created, location: @precio }
      else
        format.html { render :new }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precios/1
  # PATCH/PUT /precios/1.json
  def update
    respond_to do |format|
      if @precio.update(precio_params)
        format.html { redirect_to pets_url }
        format.json { render :show, status: :ok, location: @precio }
      else
        format.html { render :edit }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precios/1
  # DELETE /precios/1.json
  def destroy
    @precio.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precio
      @precio = Precio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precio_params
      params.require(:precio).permit(:precio, :tipo, :pet_id)
    end
end

app/helpers/efemerides_helper.rb
module EfemeridesHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/paquetes_helper.rb
module PaquetesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/respuesta_helper.rb
module RespuestaHelper
end

app/views/precios/_form.html.erb
<%= form_with(model: precio, local: true) do |form| %>
  <% if precio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(precio.errors.count, "error") %> prohibited this precio from being saved:</h2>

      <ul>
      <% precio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= form.label :precio, "Precio" %>
    <%= form.text_field :precio, id: :precio_precio, :class => 'form-control', :placeholder => "Precio $" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= form.label :tipo, "Tipo" %>
    <%= form.text_field :tipo, id: :precio_tipo, :class => 'form-control', :placeholder => "Tipo" %>
  </div>
  </div>

  <div class="field">
      <%= form.hidden_field :pet_id, id: :pet_id, :value => @pet.id %>
    </div>
    
  <div class="actions">
    <%= form.submit "Cear", :class => "btn btn-primary", data: { confirm: '¿Creará un horario, desea continuar?' } %>
  </div>
<% end %>

app/views/precios/_formm.html.erb
<%= form_with(model: precio, local: true) do |form| %>
  <% if precio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(precio.errors.count, "error") %> prohibited this precio from being saved:</h2>

      <ul>
      <% precio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= form.label :precio, "Precio" %>
    <%= form.text_field :precio, id: :precio_precio, :class => 'form-control', :placeholder => "Precio $" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= form.label :tipo, "Tipo" %>
    <%= form.text_field :tipo, id: :precio_tipo, :class => 'form-control', :placeholder => "Tipo" %>
  </div>
  </div>

  <div class="field">
      <%= form.hidden_field :pet_id, id: :pet_id %>
    </div>

  <div class="actions">
    <%= form.submit "Cear", :class => "btn btn-primary", data: { confirm: '¿Creará un horario, desea continuar?' } %>
  </div>
<% end %>

app/views/precios/edit.html.erb
<h1>Editing Precio</h1>

<%= render 'formm', precio: @precio %>

<%= link_to 'Show', @precio %> |
<%= link_to 'Back', precios_path %>

app/views/precios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Precios</h1>

<table>
  <thead>
    <tr>
      <th>Precio</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @precios.each do |precio| %>
      <tr>
        <td><%= precio.precio %></td>
        <td><%= precio.tipo %></td>
        <td><%= link_to 'Show', precio %></td>
        <td><%= link_to 'Edit', edit_precio_path(precio) %></td>
        <td><%= link_to 'Destroy', precio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Precio', new_precio_path %>

app/views/precios/new.html.erb
<div class="container">
    <h1>Crea un nuevo Horario</h1>
  <div class="row">
    <div class="col-md-6">
    <%= render 'form', precio: @precio %>
    </div>
  </div>
   <p> <%= link_to 'Back',  show_path(:id => @pet.id) %> </p>
</div>

app/views/precios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Precio:</strong>
  <%= @precio.precio %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @precio.tipo %>
</p>

<%= link_to 'Edit', edit_precio_path(@precio) %> |
<%= link_to 'Back', precios_path %>